import type { SeedMembership, SeedUnit, SeedUser } from '../seed-shared';

export const coreUsers: SeedUser[] = [
  {
    key: 'superadmin',
    fullName: 'Super Admin Sistem',
    username: 'superadmin',
    password: 'Admin@1234!',
    role: 'super_admin',
  },
  {
    key: 'kasad',
    fullName: 'Jenderal TNI Bambang Hariyanto',
    username: 'kasad',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-AD-0001',
  },
  {
    key: 'pangdam_ibb',
    fullName: 'Mayor Jenderal TNI Putranto Gatot',
    username: 'pangdam_ibb',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-KODAM-0001',
  },
  {
    key: 'kasdam_ibb',
    fullName: 'Brigadir Jenderal TNI Hendra Wijaya',
    username: 'kasdam_ibb',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-KODAM-0002',
  },
  {
    key: 'irdam_ibb',
    fullName: 'Kolonel Inf. Bambang Setiawan',
    username: 'irdam_ibb',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-KODAM-0003',
  },
  {
    key: 'asops_kasdam',
    fullName: 'Kolonel Inf. Andi Prasetya',
    username: 'asops_kasdam',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-KODAM-0004',
  },
  {
    key: 'asintel_kasdam',
    fullName: 'Kolonel Inf. Dedi Kurniawan',
    username: 'asintel_kasdam',
    password: 'Komando@123!',
    role: 'member',
    identityNumber: 'NRP-KODAM-0005',
  },
  {
    key: 'danrem_022',
    fullName: 'Kolonel Inf. Ridwan Hutapea',
    username: 'danrem_022',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-REM-0022',
  },
  {
    key: 'danrem_023',
    fullName: 'Kolonel Inf. Surya Atmaja',
    username: 'danrem_023',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-REM-0023',
  },
  {
    key: 'danrem_031',
    fullName: 'Kolonel Inf. Fadli Ramadhan',
    username: 'danrem_031',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-REM-0031',
  },
  {
    key: 'danrem_032',
    fullName: 'Kolonel Inf. Yusuf Maulana',
    username: 'danrem_032',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-REM-0032',
  },
  {
    key: 'dandenintel',
    fullName: 'Letnan Kolonel Inf. Aditya Wibowo',
    username: 'dandenintel',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-SAT-0001',
  },
  {
    key: 'dandenpom',
    fullName: 'Letnan Kolonel Cpm. Bayu Saputra',
    username: 'dandenpom',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-SAT-0002',
  },
  {
    key: 'kadenkesyah',
    fullName: 'Letnan Kolonel Ckm. dr. Reza Pahlevi',
    username: 'kadenkesyah',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-SAT-0003',
  },
  {
    key: 'danzidam',
    fullName: 'Letnan Kolonel Czi. Hario Nugroho',
    username: 'danzidam',
    password: 'Komandan@123!',
    role: 'member',
    identityNumber: 'NRP-SAT-0004',
  },
  {
    key: 'joko_susilo',
    fullName: 'Sersan Mayor Joko Susilo',
    username: 'joko_susilo',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM022-001',
  },
  {
    key: 'agus_salim',
    fullName: 'Sersan Kepala Agus Salim',
    username: 'agus_salim',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM022-002',
  },
  {
    key: 'dwi_cahyono',
    fullName: 'Sersan Dwi Cahyono',
    username: 'dwi_cahyono',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM022-003',
  },
  {
    key: 'rudi_hartanto',
    fullName: 'Sersan Mayor Rudi Hartanto',
    username: 'rudi_hartanto',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM023-001',
  },
  {
    key: 'bayu_pamungkas',
    fullName: 'Sersan Kepala Bayu Pamungkas',
    username: 'bayu_pamungkas',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM023-002',
  },
  {
    key: 'indra_lesmana',
    fullName: 'Sersan Indra Lesmana',
    username: 'indra_lesmana',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM023-003',
  },
  {
    key: 'hadi_purnomo',
    fullName: 'Sersan Mayor Hadi Purnomo',
    username: 'hadi_purnomo',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM031-001',
  },
  {
    key: 'fajar_sidiq',
    fullName: 'Sersan Kepala Fajar Sidiq',
    username: 'fajar_sidiq',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM031-002',
  },
  {
    key: 'wahyu_adi',
    fullName: 'Sersan Wahyu Adi',
    username: 'wahyu_adi',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM031-003',
  },
  {
    key: 'galih_permana',
    fullName: 'Sersan Mayor Galih Permana',
    username: 'galih_permana',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM032-001',
  },
  {
    key: 'tri_wibowo',
    fullName: 'Sersan Kepala Tri Wibowo',
    username: 'tri_wibowo',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM032-002',
  },
  {
    key: 'eko_prabowo',
    fullName: 'Sersan Eko Prabowo',
    username: 'eko_prabowo',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-REM032-003',
  },
  {
    key: 'doni_saputro',
    fullName: 'Sersan Kepala Doni Saputro',
    username: 'doni_saputro',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENINTEL-001',
  },
  {
    key: 'arif_budiman',
    fullName: 'Sersan Arif Budiman',
    username: 'arif_budiman',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENINTEL-002',
  },
  {
    key: 'maman_suherman',
    fullName: 'Sersan Kepala Maman Suherman',
    username: 'maman_suherman',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENPOM-001',
  },
  {
    key: 'yanto_kurniawan',
    fullName: 'Sersan Yanto Kurniawan',
    username: 'yanto_kurniawan',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENPOM-002',
  },
  {
    key: 'dewi_anggraini',
    fullName: 'Sersan Kepala Dewi Anggraini',
    username: 'dewi_anggraini',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENKES-001',
  },
  {
    key: 'lina_marlina',
    fullName: 'Sersan Lina Marlina',
    username: 'lina_marlina',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-DENKES-002',
  },
  {
    key: 'bagus_setiadi',
    fullName: 'Sersan Kepala Bagus Setiadi',
    username: 'bagus_setiadi',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-ZIDAM-001',
  },
  {
    key: 'catur_nugraha',
    fullName: 'Sersan Catur Nugraha',
    username: 'catur_nugraha',
    password: 'Anggota@123!',
    role: 'member',
    identityNumber: 'NRP-ZIDAM-002',
  },
];

export const seedUnits: SeedUnit[] = [
  {
    key: 'mabes_ad',
    name: 'Mabes AD',
    description: 'Markas Besar Angkatan Darat.',
    commanderKey: 'kasad',
  },
  {
    key: 'kodam_ibb',
    name: 'Kodam I/Bukit Barisan',
    description: 'Komando Daerah Militer I/Bukit Barisan.',
    commanderKey: 'pangdam_ibb',
    parentKey: 'mabes_ad',
  },
  {
    key: 'korem_022',
    name: 'Korem 022/Pantai Timur',
    description: 'Komando Resor Militer 022/Pantai Timur.',
    commanderKey: 'danrem_022',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'korem_023',
    name: 'Korem 023/Kawal Samudera',
    description: 'Komando Resor Militer 023/Kawal Samudera.',
    commanderKey: 'danrem_023',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'korem_031',
    name: 'Korem 031/Wira Bima',
    description: 'Komando Resor Militer 031/Wira Bima.',
    commanderKey: 'danrem_031',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'korem_032',
    name: 'Korem 032/Wirabraja',
    description: 'Komando Resor Militer 032/Wirabraja.',
    commanderKey: 'danrem_032',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'denintel',
    name: 'Satbalakdam - Denintel',
    description: 'Satuan pelaksana Denintel Kodam I/BB.',
    commanderKey: 'dandenintel',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'denpom',
    name: 'Satbalakdam - Denpom',
    description: 'Satuan pelaksana Denpom Kodam I/BB.',
    commanderKey: 'dandenpom',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'denkesyah',
    name: 'Satbalakdam - Denkesyah',
    description: 'Satuan pelaksana Denkesyah Kodam I/BB.',
    commanderKey: 'kadenkesyah',
    parentKey: 'kodam_ibb',
  },
  {
    key: 'zidam',
    name: 'Satbalakdam - Zidam',
    description: 'Satuan pelaksana Zidam Kodam I/BB.',
    commanderKey: 'danzidam',
    parentKey: 'kodam_ibb',
  },
];

export const coreMembershipPlan: SeedMembership[] = [
  { userKey: 'kasad', unitKey: 'mabes_ad' },
  { userKey: 'pangdam_ibb', unitKey: 'kodam_ibb' },
  { userKey: 'kasdam_ibb', unitKey: 'kodam_ibb' },
  { userKey: 'irdam_ibb', unitKey: 'kodam_ibb' },
  { userKey: 'asops_kasdam', unitKey: 'kodam_ibb' },
  { userKey: 'asintel_kasdam', unitKey: 'kodam_ibb' },
  { userKey: 'danrem_022', unitKey: 'korem_022' },
  { userKey: 'danrem_023', unitKey: 'korem_023' },
  { userKey: 'danrem_031', unitKey: 'korem_031' },
  { userKey: 'danrem_032', unitKey: 'korem_032' },
  { userKey: 'dandenintel', unitKey: 'denintel' },
  { userKey: 'dandenpom', unitKey: 'denpom' },
  { userKey: 'kadenkesyah', unitKey: 'denkesyah' },
  { userKey: 'danzidam', unitKey: 'zidam' },
  { userKey: 'joko_susilo', unitKey: 'korem_022' },
  { userKey: 'agus_salim', unitKey: 'korem_022' },
  { userKey: 'dwi_cahyono', unitKey: 'korem_022' },
  { userKey: 'rudi_hartanto', unitKey: 'korem_023' },
  { userKey: 'bayu_pamungkas', unitKey: 'korem_023' },
  { userKey: 'indra_lesmana', unitKey: 'korem_023' },
  { userKey: 'hadi_purnomo', unitKey: 'korem_031' },
  { userKey: 'fajar_sidiq', unitKey: 'korem_031' },
  { userKey: 'wahyu_adi', unitKey: 'korem_031' },
  { userKey: 'galih_permana', unitKey: 'korem_032' },
  { userKey: 'tri_wibowo', unitKey: 'korem_032' },
  { userKey: 'eko_prabowo', unitKey: 'korem_032' },
  { userKey: 'doni_saputro', unitKey: 'denintel' },
  { userKey: 'arif_budiman', unitKey: 'denintel' },
  { userKey: 'maman_suherman', unitKey: 'denpom' },
  { userKey: 'yanto_kurniawan', unitKey: 'denpom' },
  { userKey: 'dewi_anggraini', unitKey: 'denkesyah' },
  { userKey: 'lina_marlina', unitKey: 'denkesyah' },
  { userKey: 'bagus_setiadi', unitKey: 'zidam' },
  { userKey: 'catur_nugraha', unitKey: 'zidam' },
];
